(async function(){'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'Not recorded').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(paths,label){for(const path of paths){const response=await fetch(path,{cache:'no-store'});if(response.ok)return response.json()}throw new Error(`${label} file is missing from the repository root.`)}
try{
if(!window.L)throw new Error('Map library unavailable. Check your internet connection and reload.');
const [data,boundaries]=await Promise.all([load(['arbo-masterlist.json','data/gis/arbo-masterlist.json'],'ARBO masterlist'),load(['pangasinan-barangays.json','data/gis/pangasinan-barangays.json'],'Pangasinan barangay boundary')]),rows=data.organizations;
const map=L.map('map',{zoomSnap:.25,attributionControl:false,minZoom:8,maxZoom:16}).setView([16.02,120.35],9),markerLayer=L.layerGroup().addTo(map);map.getContainer().style.background='#f4f3e8';
const barangayLayer=L.geoJSON(boundaries,{style:{color:'#68766a',weight:.65,fillColor:'#e7eadf',fillOpacity:.38},onEachFeature:(feature,layer)=>layer.bindTooltip(`${feature.properties.barangay}, ${feature.properties.municipality}`,{permanent:true,direction:'center',className:'barangay-label',opacity:.9})}).addTo(map),boundaryBounds=barangayLayer.getBounds();map.fitBounds(boundaryBounds,{padding:[18,18]});
function updateLabels(){const show=map.getZoom()>=11;barangayLayer.eachLayer(layer=>show?layer.openTooltip():layer.closeTooltip())}map.on('zoomend',updateLabels);updateLabels();
const legend=L.control({position:'bottomright'});legend.onAdd=()=>{const div=L.DomUtil.create('div','map-legend');div.innerHTML='<b>ARBO status</b><span><i class="operational"></i> Operational</span><span><i class="non-operational"></i> Non-operational</span><small>Barangay labels appear when zoomed in</small>';return div};legend.addTo(map);
for(const key of ['municipality','status'])for(const value of [...new Set(rows.map(r=>r[key]).filter(Boolean))].sort())$(key).add(new Option(value,value));
const detail=r=>`<strong>${esc(r.name)}</strong><p>${esc(r.barangay)}, ${esc(r.municipality)}</p><p>Status: ${esc(r.status)}<br>Type: ${esc(r.type)}<br>ARC: ${esc(r.arc)}<br>Cluster: ${esc(r.cluster)}<br>Membership: ${esc(r.membership)}<br>ARB members: ${esc(r.arbMembership)}</p><p>${esc(r.locationBasis)}. Marker may be offset slightly where organizations share a barangay. Source: pangasinan.xlsx, Pangasinan, row ${r.sourceRow}; July 2026.</p>`;
let visible=[];
function markerPosition(coord,index,total){if(total<2)return coord;const ring=Math.floor(index/8)+1,angle=2*Math.PI*(index%8)/Math.min(total,8),distance=.0028*ring;return[coord[0]+Math.sin(angle)*distance,coord[1]+Math.cos(angle)*distance]}
function fit(){const coords=visible.filter(r=>r.coord).map(r=>r.coord);if(coords.length&&visible.length<rows.length)map.fitBounds(L.latLngBounds(coords),{padding:[35,35],maxZoom:13});else map.fitBounds(boundaryBounds,{padding:[18,18]})}
function render(){const q=$('search').value.toLowerCase().trim();visible=rows.filter(r=>(!$('municipality').value||r.municipality===$('municipality').value)&&(!$('status').value||r.status===$('status').value)&&(!q||[r.name,r.barangay,r.municipality,r.arc,r.cluster,r.arboId].join(' ').toLowerCase().includes(q)));markerLayer.clearLayers();$('directory').replaceChildren();const groups=new Map();for(const r of visible)if(r.coord){const key=r.coord.join(',');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}
for(const group of groups.values())group.forEach((r,index)=>{const operational=String(r.status).toLowerCase()==='operational',color=operational?'#16834b':'#cf3341',marker=L.circleMarker(markerPosition(r.coord,index,group.length),{radius:6,color:'#fff',weight:1.5,fillColor:color,fillOpacity:.95}).bindPopup(detail(r)).addTo(markerLayer);r.marker=marker});
for(const r of visible){const operational=String(r.status).toLowerCase()==='operational',b=document.createElement('button');b.className='record';b.innerHTML=`<strong>${esc(r.name)}</strong><small>${esc(r.barangay)}, ${esc(r.municipality)}</small><small class="status-line ${operational?'is-operational':'is-non-operational'}"><i></i>${esc(r.status)}</small><span class="badge">${r.coord?'Approximate barangay location':'Unmapped — address needs review'}</span>`;b.onclick=()=>{if(r.coord&&r.marker){map.setView(r.marker.getLatLng(),13);r.marker.openPopup()}else b.querySelector('.badge').textContent='No matching barangay boundary. Office coordinates or a confirmed address are needed.'};$('directory').appendChild(b)}
const mapped=visible.filter(r=>r.coord).length,operational=visible.filter(r=>String(r.status).toLowerCase()==='operational').length;$('stats').textContent=`${visible.length} of ${rows.length} organizations · ${operational} operational · ${visible.length-operational} non-operational · ${mapped} mapped approximately`;if(!visible.length)$('directory').textContent='No organizations match these filters.';fit()}
$('search').oninput=render;$('municipality').onchange=render;$('status').onchange=render;$('fit').onclick=fit;render();
}catch(error){$('stats').textContent=error.message;}
})();
